github:
  token: ${GITHUB_TOKEN}
  issueRepo: airfocusio/trivy-gh-test
files: ^/deployment\.yaml$
mitigations:
- comment:  Local exec only
  match:
    packageName:
    - sh
    - bash
- comment: Internal container
  match:
    cvss:
      av:
      - N
ignores:
- match:
    id:
    - CVE-0
