name: 'Trivy GitHub'
description: ''
inputs:
  github-token:
    description: 'github token'
    required: true
  args:
    description: 'command line args'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: docker://ghcr.io/airfocusio/trivy-gh:latest
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        args: ${{ inputs.args }}
