github:
  token: ${GITHUB_TOKEN}
  issueRepo: owner/repo
files:
- f1$
- ^f2
mitigations:
- key: not-used
  label: Package not used
- key: no-public-networking
  label: No public networking
policies:
- comment: |
    Comment 1
  match:
    id:
    - CVE-0
  ignore: true
- comment: Comment 2
  match:
    artifactNameShort: debian
  mitigate: not-used
- match:
    packageName:
    - sh
    - bash
  mitigate: not-used
- match:
     class: os-pkgs
  mitigate: not-used
- match:
    cvss:
      av:
      - N
      - L
      ac: H
      pr: H
      ui: N
      s: C
      c: H
      i: H
      a: H
  mitigate: no-public-networking
- match:
    not:
      id: CVE-1
- match:
    and:
    - id: CVE-2
    - id: CVE-3
- match:
    or:
    - id: CVE-4
    - id: CVE-5
