github:
  token: ${GITHUB_TOKEN}
  issueRepo: owner/repo
files:
- f1$
- ^f2
mitigations:
- comment: Comment 2
  match:
    artifactNameShort: debian
- match:
    packageName:
    - sh
    - bash
- match:
     class: os-pkgs
- match:
    cvss:
      av:
      - N
      - L
      ac: H
      pr: H
      ui: N
      s: C
      c: H
      i: H
      a: H
- match:
    not:
      id: CVE-1
- match:
    and:
    - id: CVE-2
    - id: CVE-3
- match:
    or:
    - id: CVE-4
    - id: CVE-5
ignores:
- comment: |
    Comment 1
  match:
    id:
    - CVE-0
